version: '3'
services:

  traquer-julia-server:
    image: traquer-julia-server:${SYST_USER_TAG}
    deploy:
      resources:
        limits:
          cpus: '1.5'
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-julia
      args:
        SSH_MASTER_USER: traquer
        SSH_MASTER_PWD: ${SSH_PASSWORD}
    networks:
      - julia-middleware
    container_name: traquer-julia-server-${SYST_USER_TAG}
    ports:
      - "${JULIA_API_PORT}:8095"
      - "${SSH_PORT}:22"
#    restart: no # restart the container together with the daemon
#    env_file:
#      - traquer-julia-server.env
    volumes:
      - ${TRAQUER_DATA_DIR}:/home/traquer/DATA
      - ${TRAQUER_PENDING_INPUT_FILES_DIR}:/home/traquer/FILES_EXCHANGE/PENDING
      - ${TRAQUER_PROCESSING_INPUT_FILES_DIR}:/home/traquer/FILES_EXCHANGE/PROCESSING
      - ${TRAQUER_DONE_INPUT_FILES_DIR}:/home/traquer/FILES_EXCHANGE/DONE
      - ${TRAQUER_INPUT_FILES_PROBLEMS_DIR}:/home/traquer/FILES_EXCHANGE/PROBLEMS
      - ${TRAQUER_BACKEND_SRC_CODE_DIR}:/home/traquer/CODE/TRAQUER.jl
      - ./volumes/julia-server/.julia:/home/traquer/.julia:z
      - ./volumes/julia-server/jwt_signing_keys.json:/home/traquer/jwt_signing_keys.json
      - ./volumes/julia-server/.pgpass:/home/traquer/.pgpass:z
      - ${TRAQUER_FRONTEND_SRC_CODE_DIR}:/home/traquer/tmp/traquer-frontend-angular
    command: tail -F /dev/null # Prevents the container from exiting
    tty: true

  traquer-pgbouncer:
    image: edoburu/pgbouncer:1.15.0
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - POOL_MODE=session
      - ADMIN_USERS=postgres,${DB_USER}
      - IGNORE_STARTUP_PARAMETERS=options
      - SERVER_TLS_SSLMODE=prefer
    networks:
      julia-middleware:
        aliases:
          - pgbouncer

  traquer-nginx-server:
    image: traquer-nginx-server:${SYST_USER_TAG}
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-nginx
    container_name: traquer-nginx-server-${SYST_USER_TAG}
    links:
      - "traquer-julia-server"
    ports:
      - ${NGINX_PORT}:80
    networks:
      -  nginx-middleware
    restart: always # restart the container together with the daemon
    volumes:
      - ./volumes/nginx-server/html/traquer-frontend-angular:/usr/share/nginx/html/traquer-frontend-angular
      - ./volumes/nginx-server/html/traquer-frontend-angular-en:/usr/share/nginx/html/traquer-frontend-angular-en
      - ./volumes/nginx-server/conf/traquer-frontend-angular.nginx.conf:/etc/nginx/conf.d/traquer-frontend-angular.nginx.conf

networks:
  julia-middleware:
  nginx-middleware:

